### PR TITLE
Compiles in Crystal 0.16.0

### PR DESCRIPTION
**Pull request by DougEverly**
Added type annotations where necessary. Compiles.

### CODE REVIEW

**Comment by datanoise** [comment]
thanks for the PR! Unfortunately, crystal team has redesigned Channel API by implementing the ability to close a channel, but not providing a way to receive from a channel with a specified timeout. My initial Timed::Channel implementation is broken under the current crystal version. So there is no point to continue this effort until a timed channel receive is implemented by the crystal team.

**Comment by DougEverly** [comment]
Thats unfortunate, as the work you’ve done looks great. I use RabbitMQ in my day job and would love to experiment with Crystal in that environment.

Thanks for the info on where its currently broken.

- Doug

**Comment by datanoise** [comment]
Good news is that I was able to fix it for now.

**Comment by DougEverly** [comment]
Yes, it works now!

Thank you,
- Doug

**Pull request merged**
